### PR TITLE
Update new modekind to match Lambdahack

### PR DESCRIPTION
**Pull request by bulbousBullfrog**
After updating Lambdahack for the modes, splitting text information describing the mission types into more specific fields regarding mission motivation and mission tips, this is an attempt to make Allure compatible.

### CODE REVIEW

**Comment by bulbousBullfrog** [comment]
Don't know if you want to modify the rules text as well to be more similar to that of Lamdahack or if it is best to leave as-is. If you do want that to be changed let me know and I will add a commit to this PR

**Comment by Mikolaj** [comment]
Yes, we definitely need the rules improved analogously as in LH. But you are right merging this PR ASAP and working on the rules overhaul without the pressure makes sense as well. You call.

**Comment by bulbousBullfrog** [comment]
Okay, I will merge this into master in case you want to work on this project before the rule text improvements get added in. I will add those next time I get a chance. Thanks!

**Comment by Mikolaj** [comment]
Thank you!

**Pull request merged**
