### PR TITLE
Clarify the game rules

### PR DESCRIPTION
**Pull request by dmytroshytikov**
I think it is a good explanation of how to play.

Next, I'll write some ideas about the squad tactics

### CODE REVIEW

**Comment by Mikolaj** [comment]
Thank you very much @dmytroshytikov! Before i read closely, where do you envision the new text should go? Into the game manual PLAYING.md or into its Frequently Asked Questions section or into the in-game help text, the default version of which is additionally dumped into the file you modified (the actual in-game versions differ from the dump only in formatting and in that they list descriptions of additional macros and commands defined by the player)?

**Comment by dmytroshytikov** [comment]
Well, originally, it was intended to be in the in-game help, but its size is pretty large. Maybe, it is possible to put it into the 'PLAYING.md' file but add a reference to the in-game help.

**Comment by dmytroshytikov** [comment]
I think this information will look better in the PLAYING.md file. I did not realize that all this text is too long for a brief in-game help. I will retract these suggestions and pull back this request.

**Comment by Mikolaj** [comment]
Thank you for closing. We've moved to the other one.

**Pull request closed without merging**
